### ISSUE TITLE
Attention-based Spatial Alignment

### ISSUE THREAD

**Issue by yubin2020** [yassouali/SCL#2]
Excuse me,I want to ask:
What is the two input features of Attention-based Spatial Alignment Net? Do the input two features come from the two types of  augment respectively?(Standard aug and simclr augment)
But in the program,I find that the two input features are same.(Copy feature_a as fearure_b)
Thanks!

**Comment by yassouali** [comment]
Hi @yubin2020 

The implementation is done to be as general as possible, so the module can take any two tensors A and B, and aligns each example in A with each example in B.

For example, as you said, A can be origianal batch and B the augmented batch, but since we use the supervised contrastive loss, we also want to contrast exemples inside the same batch, so in thsi case you can also pass [A & B] and [A & B] for both to contrast a larger number of examples (while removing self contrasting in the loss), and this works a bit better. 

So in our case, we use all example and simply pass the same tensor of features (current batch).

Hope this helps.

**Comment by yubin2020** [comment]
Thank you very much for your kind attention personal response！
As you said，when we use A (origianal batch ) and B (augmented batch) as the two inputs, we can get two different similarity&nbsp;matrices&nbsp;through the Attention-based Spatial Alignment Net.But when we&nbsp;pass [A &amp; B] and [A &amp; B] ,we can end up with&nbsp;two identical similarity matrices to&nbsp;calculate loss (because of the two same inputs).So if we use&nbsp;[A &amp; B]&nbsp;and [A &amp; B]&nbsp;as input,&nbsp;we&nbsp;only need to calculate the similarity once (equivalent to removing the branch of&nbsp;calculating the second similarity).
Please,do I understand this correctly?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yassouali/SCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 凌晨1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yassouali/SCL] Attention-based Spatial Alignment (Issue #2)





 
Hi @yubin2020
 
The implementation is done to be as general as possible, so the module can take any two tensors A and B, and aligns each example in A with each example in B.
 
For example, as you said, A can be origianal batch and B the augmented batch, but you can also pass [A &amp; B] and [A &amp; B] for both to contrast a larger number of examples (while removing self contrasting in the loss), and this works a bit better.
 
So in our case, we use all example and simply pass the same tensor of features (current batch).
 
Hope this helps.

**Comment by yassouali** [comment]
Yes @yubin2020 

That is correct, if you want to make the computation more efficient, you can only compute it once in our case

**Comment by yubin2020** [comment]
Thanks for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yassouali/SCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月21日(星期天) 凌晨3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yassouali/SCL] Attention-based Spatial Alignment (Issue #2)





 
Yes @yubin2020
 
That is correct, if you want to make the computation more efficient, you can only compute it once in our case

**Comment by yubin2020** [comment]
Excuse me, I also want to ask the program(the simclr loss). If I use A(origianal batch) and B(augmented batch) as input, where else do I still need to change ? (Known:feature_a is A, feature_b is B, the [mask = mask.repeat(2, 2)] is not needed )&nbsp;
Thanks!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yassouali/SCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 凌晨1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yassouali/SCL] Attention-based Spatial Alignment (Issue #2)





 
Hi @yubin2020
 
The implementation is done to be as general as possible, so the module can take any two tensors A and B, and aligns each example in A with each example in B.
 
For example, as you said, A can be origianal batch and B the augmented batch, but you can also pass [A &amp; B] and [A &amp; B] for both to contrast a larger number of examples (while removing self contrasting in the loss), and this works a bit better.
 
So in our case, we use all example and simply pass the same tensor of features (current batch).
 
Hope this helps.

**Comment by yassouali** [comment]
in your case, no need to remove self contrastive (the diagonals of the similarity matrix), since all the two features are different

all you need to do is simply passing both features to the loss (features_a & features_b, see https://github.com/yassouali/SCL/blob/0a45738435d27781e26ccf621a23177617c2b084/losses.py#L80), and this will remove the self masking by using a mask of ones:

**Comment by yubin2020** [comment]
I can understand what you mean.In this case,the '2N' of the loss will change&nbsp; to 'N'.
But I don't&nbsp; understand how to modify the code. Can you explain it a little？
Thanks!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yassouali/SCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月25日(星期四) 凌晨0:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yassouali/SCL] Attention-based Spatial Alignment (Issue #2)





 
in your case, no need to remove self contrastive (the diagonals of the similarity matrix), since all the two features are different
 
exact line: https://github.com/yassouali/SCL/blob/0a45738435d27781e26ccf621a23177617c2b084/losses.py#L80

**Comment by yassouali** [comment]
I just updated the loss, now it should be working by simply passing original features as features_a and augmented features as features_b

**Comment by yubin2020** [comment]
Thanks for your help!I mainly study few-shot action recognition,I want to learn from your work！
Hope to have more opportunities to communicate with you in the future！
Good luck！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yassouali/SCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月25日(星期四) 凌晨1:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yassouali/SCL] Attention-based Spatial Alignment (Issue #2)





 
I just updated the loss, now it should be working by simply passing original features as features_a and augmented features as features_b
